Capture logs for mariadb_ctl script
- We are capturing the stdout and stderr into
  /var/vcap/sys/log/mariadb_ctl{, err}.log
- We changed the logger priority from local1.error to user.error

[#118612267]

Signed-off-by: Morgan Fine <mfine@pivotal.io>

diff --git a/jobs/mysql/templates/mariadb_ctl.erb b/jobs/mysql/templates/mariadb_ctl.erb
--- a/jobs/mysql/templates/mariadb_ctl.erb
+++ b/jobs/mysql/templates/mariadb_ctl.erb
@@ -18,10 +18,13 @@ TMP_DIR=/var/vcap/data/mysql/tmp
 PRESTART_MARKER_FILE=/var/vcap/sys/run/prestart_marker
 
 source /var/vcap/packages/cf-mysql-common/pid_utils.sh
+source /var/vcap/packages/cf-mysql-common/syslog_utils.sh
+
+tee_output_to_sys_log "/var/vcap/sys/log"
 
 # add mysql to path
 if [ ! -f /usr/local/bin/mysql ]; then
-  log "Adding mysql to path"
+  echo "Adding mysql to path"
   ln -s /var/vcap/packages/mariadb/bin/mysql /usr/local/bin
 fi
 
@@ -30,6 +33,11 @@ export PATH=$PATH:/var/vcap/packages/xtrabackup/bin
 
 # add perl libraries to perl env
 export PERL5LIB=$PERL5LIB:/var/vcap/packages/xtrabackup/lib/perl/5.18.2
+
+# setup log directory and file for daemon process
+mkdir -p $LOG_DIR
+touch $LOG_FILE
+chown -R vcap:vcap $LOG_DIR
 
 ulimit -n <%= p('cf_mysql.mysql.max_open_files') %>
 
@@ -43,7 +51,7 @@ case $1 in
 
   start)
     if [ ! -f ${PRESTART_MARKER_FILE} ]; then
-      log "this bosh version and/or stemcell version is not pre-start compatible"
+      >&2 echo "This bosh version and/or stemcell version is not pre-start compatible"
       exit 1
     fi
 
@@ -53,24 +61,19 @@ case $1 in
     mkdir -p $TMP_DIR
     chown -R vcap:vcap $TMP_DIR
 
-    log "start script: checking for existing instance of $PROC_NAME"
+    echo "Checking for existing instance of $PROC_NAME"
     set +e
     $(source /var/vcap/packages/cf-mysql-common/pid_utils.sh; pid_guard $PIDFILE $PROC_NAME)
     pg_exit_code=$?
-    log "start script: pg_exit_code: $pg_exit_code"
+    echo "pg_exit_code: $pg_exit_code"
     if [ $pg_exit_code -eq 1 ]; then
-      log "start script: $PROC_NAME already running. Exiting 0 so that monit doesn't think that execution failed"
+      echo "${PROC_NAME} already running. Exiting 0 so that monit doesn't think that execution failed"
       exit 0
     fi
     set -e
 
     # Start syslog forwarding
     /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $MARIADB_JOB_DIR/config
-
-    mkdir -p $LOG_DIR
-    touch $LOG_FILE
-    chown -R vcap:vcap $LOG_DIR
-    date >> $LOG_FILE 2>> $LOG_FILE
 
     # It is surprisingly hard to get the config file location passed in
     # on the command line to the mysql.server script. This is easier.
@@ -81,37 +84,34 @@ case $1 in
     chown -R vcap:vcap $CONFIG_DIR
 
     if ! test -d ${datadir}; then
-      log "start script: making ${datadir} and running /var/vcap/packages/mariadb/scripts/mysql_install_db"
+      echo "start script: making ${datadir} and running /var/vcap/packages/mariadb/scripts/mysql_install_db"
       mkdir -p ${datadir}
       /var/vcap/packages/mariadb/scripts/mysql_install_db \
              --basedir=/var/vcap/packages/mariadb \
              --user=vcap \
-             --datadir=${datadir} >> $LOG_FILE 2>> $LOG_FILE
+             --datadir=${datadir}
     fi
     chown -R vcap:vcap ${datadir}
 
     cd $MARIADB_CTRL_PACKAGE
 
-    log "start script: starting mariadb_ctrl..."
+    echo "start script: starting mariadb_ctrl..."
     su vcap -c \
     "PATH=$PATH PERL5LIB=$PERL5LIB $MARIADB_CTRL_PACKAGE/bin/mariadb_ctrl \
              -configPath=$CONFIG_FILE \
              2>&1 \
              | tee -a $LOG_FILE \
-             | logger -p local1.error -t mariadb_ctrl &"
+             | logger -p user.error -t mariadb_ctrl &"
 
-    log "start script: completed starting mariadb_ctrl."
+    echo "start script: completed starting mariadb_ctrl."
     ;;
 
   stop)
-    log "stop script: stopping mariadb_ctrl..."
-    mkdir -p $LOG_DIR
-    chown -R vcap:vcap $LOG_DIR
-    date >> $LOG_FILE 2>> $LOG_FILE
+    echo "stop script: stopping mariadb_ctrl..."
 
-    log "stop script: stopping node $JOB_INDEX" >> $LOG_FILE
+    echo "stop script: stopping node $JOB_INDEX"
     kill_and_wait $PIDFILE
-    log "stop script: completed stopping mariadb_ctrl"
+    echo "stop script: completed stopping mariadb_ctrl"
     ;;
 
   *)
