Use pre-start and start commands now that they are separated
- Also, set pipefail so that the scripts will fail properly

[#131014785]

Signed-off-by: Aaron Hurley <ahurley@pivotal.io>

diff --git a/jobs/mysql/templates/pre-start-execution.erb b/jobs/mysql/templates/pre-start-execution.erb
--- a/jobs/mysql/templates/pre-start-execution.erb
+++ b/jobs/mysql/templates/pre-start-execution.erb
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
 
 <% if !p('cf_mysql.mysql.disable_auto_sst') %>
 export DISABLE_SST=0
@@ -42,11 +43,11 @@ pid_guard $PIDFILE $PROC_NAME
 cd $MARIADB_CTRL_PACKAGE
 
 $MARIADB_CTRL_PREFIX_CMD \
-"PATH=$PATH PERL5LIB=$PERL5LIB $MARIADB_CTRL_PACKAGE/bin/mariadb_ctrl \
+"PATH=$PATH PERL5LIB=$PERL5LIB $MARIADB_CTRL_PACKAGE/bin/mariadb_ctrl-prestart \
          -configPath=$CONFIG_FILE \
-         -prestart=true \
          2>&1 \
          | tee -a $LOG_FILE \
          | logger -p local1.error -t mariadb_ctrl"
 
+log "pre-start execution script: pre-start completed with error code $?"
 log "pre-start execution script: completed pre-start execution"
