Use gospace style layout for go projects
So we can eventually move deps into the release and start developing from within the release itself [#86649208]

diff --git a/packages/galera-healthcheck/packaging b/packages/galera-healthcheck/packaging
--- a/packages/galera-healthcheck/packaging
+++ b/packages/galera-healthcheck/packaging
@@ -1,13 +1,19 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+#!/usr/bin/env bash
 
-#compile
+set -e
+set -u
+
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
+export REPO=$GOPATH/src/github.com/cloudfoundry-incubator/galera-healthcheck
+export GOPATH=$GOPATH:$REPO/Godeps/_workspace
+
 export GOROOT=$(readlink -nf /var/vcap/packages/golang)
 export PATH=$GOROOT/bin:$PATH
-REPO=galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck
-
-export GOPATH=$PWD/$REPO/Godeps/_workspace:$PWD/galera-healthcheck
 
 go install github.com/cloudfoundry-incubator/galera-healthcheck
 
-cp galera-healthcheck/bin/galera-healthcheck $BOSH_INSTALL_TARGET/galera-healthcheck-executable
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
+
diff --git a/packages/mariadb_ctrl/packaging b/packages/mariadb_ctrl/packaging
--- a/packages/mariadb_ctrl/packaging
+++ b/packages/mariadb_ctrl/packaging
@@ -1,15 +1,22 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+#!/usr/bin/env bash
 
-#compile
+set -e
+set -u
+
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
+export REPO=$GOPATH/src/github.com/cloudfoundry/mariadb_ctrl
+
 export GOROOT=$(readlink -nf /var/vcap/packages/golang)
 export PATH=$GOROOT/bin:$PATH
 
-export GOPATH=$PWD/mariadb_ctrl
-
 go install github.com/cloudfoundry/mariadb_ctrl
 
-cp mariadb_ctrl/bin/mariadb_ctrl $BOSH_INSTALL_TARGET/mariadb_ctrl-executable
-cp mariadb_ctrl/src/github.com/cloudfoundry/mariadb_ctrl/mysql_upgrade.sh $BOSH_INSTALL_TARGET/mysql_upgrade.sh
-cp mariadb_ctrl/src/github.com/cloudfoundry/mariadb_ctrl/mysql_daemon.sh $BOSH_INSTALL_TARGET/mysql_daemon.sh
-cp mariadb_ctrl/src/github.com/cloudfoundry/mariadb_ctrl/show_databases.sh $BOSH_INSTALL_TARGET/show_databases.sh
+cp $BOSH_INSTALL_TARGET/src/github.com/cloudfoundry/mariadb_ctrl/mysql_upgrade.sh  $BOSH_INSTALL_TARGET/bin/mysql_upgrade.sh
+cp $BOSH_INSTALL_TARGET/src/github.com/cloudfoundry/mariadb_ctrl/mysql_daemon.sh   $BOSH_INSTALL_TARGET/bin/mysql_daemon.sh
+cp $BOSH_INSTALL_TARGET/src/github.com/cloudfoundry/mariadb_ctrl/show_databases.sh $BOSH_INSTALL_TARGET/bin/show_databases.sh
+
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
+
diff --git a/packages/route-registrar/packaging b/packages/route-registrar/packaging
--- a/packages/route-registrar/packaging
+++ b/packages/route-registrar/packaging
@@ -1,27 +1,19 @@
 #!/usr/bin/env bash
 
-#set -e -x
-#
-#cd route-registrar
-#
-#export GOROOT=`pwd`
-#export GOPATH=$BOSH_INSTALL_TARGET:${REPO_DIR}/Godeps/_workspace
-#
-#/var/vcap/packages/golang/bin/go build -o ${BOSH_INSTALL_TARGET}/route-registrar ./...
-#
+set -e
+set -u
 
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
-set +x
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
+export REPO=$GOPATH/src/github.com/cloudfoundry-incubator/route-registrar
+export GOPATH=$GOPATH:$REPO/Godeps/_workspace
 
-#compile
 export GOROOT=$(readlink -nf /var/vcap/packages/golang)
-export PATH=/var/vcap/packages/git/bin:$PATH
 export PATH=$GOROOT/bin:$PATH
-REPO=route-registrar/src/github.com/cloudfoundry-incubator/route-registrar
-
-export GOPATH=$PWD/$REPO/Godeps/_workspace:$PWD/route-registrar
 
 go install github.com/cloudfoundry-incubator/route-registrar
 
-cp route-registrar/bin/route-registrar $BOSH_INSTALL_TARGET/route-registrar
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
+
