Bump src/cf-mysql-broker
Bump cloudfoundry/cf-mysql-broker:
  Lyle Franklin:
     Fix defect where sync_service_instances initializer would fail on fresh deploy ( Travis Unknown )

[#105336102]

diff --git a/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb b/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
--- a/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
+++ b/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
@@ -33,31 +33,44 @@ case $1 in
 
     # Run the migrations only on the first node
     if [ $JOB_INDEX -eq 0 ]; then
-      echo "Running db:create and db:migrate at `date`" \
-          | tee -a $LOG_DIR/db_migrate.combined.log \
-          | logger -p local1.error -t mysql-broker-dbmigrate
-      cd $PACKAGE_DIR
+      pushd $PACKAGE_DIR
 
-      set +e
-      bundle exec rake db:create 2>&1 \
-          | tee -a $LOG_DIR/db_migrate.combined.log \
-          | logger -p local1.error -t mysql-broker-dbcreate
+        # Create DB and run migrations
+        set +e
+        bundle exec rake db:create 2>&1 \
+            | tee -a $LOG_DIR/db_migrate.combined.log \
+            | logger -p local1.error -t mysql-broker-dbcreate
 
-      bundle exec rake db:migrate 2>&1 \
-          | tee -a $LOG_DIR/db_migrate.combined.log \
-          | logger -p local1.error -t mysql-broker-dbmigrate
-
-      EXIT_STATUS=$?
-      set -e
-
-      if [ $EXIT_STATUS != 0 ]; then
-        echo "Migrations failed at `date`" \
+        bundle exec rake db:migrate 2>&1 \
             | tee -a $LOG_DIR/db_migrate.combined.log \
             | logger -p local1.error -t mysql-broker-dbmigrate
-        exit 1
-      fi
 
-      cd -
+        EXIT_STATUS=$?
+        set -e
+
+        if [ $EXIT_STATUS != 0 ]; then
+          echo "Migrations failed at `date`" \
+              | tee -a $LOG_DIR/db_migrate.combined.log \
+              | logger -p local1.error -t mysql-broker-dbmigrate
+          exit 1
+        fi
+
+        # Sync size of existing service instances to match plans in manifest
+        set +e
+        bundle exec rake broker:sync_plans_in_db 2>&1 \
+            | tee -a $LOG_DIR/cf-mysql-broker.log \
+            | logger -p local1.error -t mysql-broker-plans
+
+        EXIT_STATUS=$?
+        set -e
+
+        if [ $EXIT_STATUS != 0 ]; then
+          echo "Failed to sync broker plans at `date`" \
+              | tee -a $LOG_DIR/cf-mysql-broker.log \
+              | logger -p local1.error -t mysql-broker-plans
+          exit 1
+        fi
+      popd
     fi
 
     bundle exec unicorn -c $JOB_DIR/config/unicorn.conf.rb 2>&1 \
