Refactor MySQL ctrl scripts for consistency
* Packaging includes compilation
* Executables have unique names for accurate pid finding (monit)

[#75989336]

diff --git a/packages/mariadb_ctrl/packaging b/packages/mariadb_ctrl/packaging
--- a/packages/mariadb_ctrl/packaging
+++ b/packages/mariadb_ctrl/packaging
@@ -1,3 +1,19 @@
-set -e -x
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
-cp -a mariadb_ctrl/* ${BOSH_INSTALL_TARGET}
+#compile
+export GOROOT=$(readlink -nf /var/vcap/packages/golang)
+export PATH=$GOROOT/bin:$PATH
+
+export GOPATH=$PWD/mariadb_ctrl
+
+echo "PWD:" $PWD
+echo "GOPATH:" $GOPATH
+echo "ls:" `ls`
+
+echo "ls - inside:" `ls mariadb_ctrl`
+
+go install mariadb_ctrl
+
+cp mariadb_ctrl/bin/mariadb_ctrl $BOSH_INSTALL_TARGET/mariadb_ctrl-executable
+
